# Generated by Django 4.2.9 on 2025-07-07 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.ForeignKey(default='Worker', on_delete=django.db.models.deletion.CASCADE, to='tasks_manager.position'),
        ),
    ]
