# Generated by Django 4.2.9 on 2025-07-20 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks_manager.organization'),
        ),
        migrations.AlterField(
            model_name='project',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks_manager.organization'),
        ),
        migrations.AlterField(
            model_name='task',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks_manager.organization'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks_manager.organization'),
        ),
        migrations.AlterField(
            model_name='team',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks_manager.organization'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks_manager.organization'),
        ),
    ]
